url: 'https://www.beracah.ca'
title: 'Beracah Counselling'
description: 'Hazel Mayhew - Beracah Counselling'
favicon: favicon.png
subtitle:
  Hazel Mayhew, MA
  •
  hazel<span class='hidden'>13</span>@<span class='hidden'>37</span>beracah.ca
  •
  403-<span class='hidden'>123</span>477-<span class='hidden'>456</span>8772
